-- MySQL Script generated by MySQL Workbench
-- 04/02/15 15:22:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema py
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `py` ;

-- -----------------------------------------------------
-- Schema py
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `py` DEFAULT CHARACTER SET utf8 ;
USE `py` ;

-- -----------------------------------------------------
-- Table `py`.`banner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`banner` ;

CREATE TABLE IF NOT EXISTS `py`.`banner` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(200) NULL DEFAULT NULL COMMENT '广告图片url',
  `description` VARCHAR(200) NULL DEFAULT NULL COMMENT '广告说明',
  `index` INT(11) NULL DEFAULT '0' COMMENT '广告主题',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '广告图片';


-- -----------------------------------------------------
-- Table `py`.`coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`coupon` ;

CREATE TABLE IF NOT EXISTS `py`.`coupon` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type_id` INT(11) NULL DEFAULT NULL,
  `param_1` DECIMAL(10,2) NOT NULL,
  `param_2` DECIMAL(10,2) NULL DEFAULT NULL,
  `removed` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '优惠券表';


-- -----------------------------------------------------
-- Table `py`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`manager` ;

CREATE TABLE IF NOT EXISTS `py`.`manager` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(45) NOT NULL COMMENT '用户名',
  `pwd` VARCHAR(200) NOT NULL COMMENT '密码',
  `role_id` INT(11) NULL DEFAULT NULL COMMENT '预留字段  角色id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '管理员表';


-- -----------------------------------------------------
-- Table `py`.`manager_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`manager_access` ;

CREATE TABLE IF NOT EXISTS `py`.`manager_access` (
  `manager_id` INT(11) NOT NULL,
  `user` INT(11) NULL DEFAULT NULL,
  `user_object` INT(11) NULL DEFAULT NULL,
  `user_lease_logs` INT(11) NULL DEFAULT NULL,
  `coupon` INT(11) NULL DEFAULT NULL,
  `banner` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`manager_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '管理员权限表';


-- -----------------------------------------------------
-- Table `py`.`object_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`object_category` ;

CREATE TABLE IF NOT EXISTS `py`.`object_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '分类名称',
  `description` VARCHAR(45) NULL DEFAULT NULL COMMENT '分类描述',
  `removed` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '物品分类表';


-- -----------------------------------------------------
-- Table `py`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user` ;

CREATE TABLE IF NOT EXISTS `py`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(45) NULL DEFAULT NULL COMMENT '手机号码',
  `email_address` VARCHAR(200) NULL DEFAULT NULL COMMENT 'email',
  `pwd` VARCHAR(200) NOT NULL COMMENT '密码',
  `created_on` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `status` INT(11) NULL DEFAULT '0' COMMENT '状态\n0 未验证\n1 手机号已验证\n2 邮箱地址已验证\n3 两者已验证',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `py`.`user_bank_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user_bank_card` ;

CREATE TABLE IF NOT EXISTS `py`.`user_bank_card` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL COMMENT '用户id',
  `card_no` VARCHAR(45) NOT NULL COMMENT '默认卡号',
  `card_from` VARCHAR(45) NOT NULL COMMENT '银行卡号',
  `status` INT(11) NULL DEFAULT '0',
  `removed` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = '银行帐号表';


-- -----------------------------------------------------
-- Table `py`.`user_evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user_evaluation` ;

CREATE TABLE IF NOT EXISTS `py`.`user_evaluation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL COMMENT '用户id',
  `observer_id` INT(11) NOT NULL COMMENT '评价者的id',
  `level` INT(11) NOT NULL,
  `description` VARCHAR(400) NOT NULL COMMENT '评价内容',
  `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评价时间',
  `type_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '用户评价表';


-- -----------------------------------------------------
-- Table `py`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user_info` ;

CREATE TABLE IF NOT EXISTS `py`.`user_info` (
  `user_id` INT(11) NOT NULL COMMENT '用户id',
  `nick_name` VARCHAR(20) NULL DEFAULT NULL COMMENT '用户呢称',
  `real_name` VARCHAR(20) NULL DEFAULT NULL COMMENT '真实姓名',
  `card_no` VARCHAR(20) NULL DEFAULT NULL COMMENT '默认的银行卡号',
  `qq_number` VARCHAR(20) NULL DEFAULT NULL COMMENT 'QQ号码',
  `identity_valid` VARCHAR(45) NULL DEFAULT '0',
  `address` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户信息表';


-- -----------------------------------------------------
-- Table `py`.`user_key`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user_key` ;

CREATE TABLE IF NOT EXISTS `py`.`user_key` (
  `user_id` INT(11) NOT NULL,
  `key` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `py`.`user_key_temp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user_key_temp` ;

CREATE TABLE IF NOT EXISTS `py`.`user_key_temp` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(200) NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `py`.`user_lease_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user_lease_logs` ;

CREATE TABLE IF NOT EXISTS `py`.`user_lease_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `object_id` INT(11) NOT NULL COMMENT '物品id',
  `lessor_id` INT(11) NOT NULL,
  `lessee_id` INT(11) NOT NULL,
  `remark` VARCHAR(400) NULL DEFAULT NULL COMMENT '评论',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '数量',
  `deal_no` VARCHAR(200) NULL DEFAULT NULL,
  `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '租赁时间',
  `status` INT(11) NULL DEFAULT '0' COMMENT '状态',
  `removed` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = '用户租赁记录表';


-- -----------------------------------------------------
-- Table `py`.`user_object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user_object` ;

CREATE TABLE IF NOT EXISTS `py`.`user_object` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL COMMENT '用户id',
  `cat_id` INT(11) NOT NULL COMMENT '标题',
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NOT NULL COMMENT '物品信息描述',
  `params` VARCHAR(1000) NULL DEFAULT NULL COMMENT '物品参数',
  `price_day` DECIMAL(10,2) NOT NULL COMMENT '租金',
  `price_pledge` DECIMAL(10,2) NOT NULL COMMENT '押金',
  `quantity` INT(11) NOT NULL COMMENT '数量',
  `return_way` INT(11) NOT NULL COMMENT '归还方式',
  `send_way` INT(11) NOT NULL COMMENT '交易方式 租主送？ 租者取？',
  `published_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间',
  `modified_on` DATETIME NULL DEFAULT NULL COMMENT '维修时间',
  `price_express` DECIMAL(10,2) NULL DEFAULT NULL,
  `contact_name` VARCHAR(45) NOT NULL,
  `contact_number` VARCHAR(45) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `status` INT(11) NULL DEFAULT '0' COMMENT '状态',
  `removed` INT(11) NULL DEFAULT '0',
  `price_month` DECIMAL(10,2) NOT NULL COMMENT '月租金',
  `invoice_type` INT(11) NULL DEFAULT NULL,
  `shortest_lease` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = '租赁物品信息表';


-- -----------------------------------------------------
-- Table `py`.`user_own_coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user_own_coupon` ;

CREATE TABLE IF NOT EXISTS `py`.`user_own_coupon` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL COMMENT '用户id',
  `coupon_id` VARCHAR(45) NOT NULL COMMENT '优惠券id',
  `expiry_date_start` DATETIME NOT NULL COMMENT '优惠券的截止日期',
  `duration_days` INT(11) NOT NULL COMMENT '优惠券有效期剩余天数',
  `removed` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '优惠券';


-- -----------------------------------------------------
-- Table `py`.`user_requirement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `py`.`user_requirement` ;

CREATE TABLE IF NOT EXISTS `py`.`user_requirement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL COMMENT '发布者id',
  `title` VARCHAR(20) NOT NULL COMMENT '标题',
  `description` VARCHAR(200) NOT NULL COMMENT '说明',
  `status` INT(11) NULL DEFAULT '0' COMMENT '状态',
  `removed` INT(11) NULL DEFAULT '0' COMMENT '已删除',
  `published_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COMMENT = '用户需求';

USE `py` ;

-- -----------------------------------------------------
-- Placeholder table for view `py`.`v_user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `py`.`v_user_details` (`id` INT, `phone_number` INT, `email_address` INT, `pwd` INT, `created_on` INT, `status` INT, `user_id` INT, `nick_name` INT, `real_name` INT, `card_no` INT, `qq_number` INT, `identity_valid` INT, `address` INT);

-- -----------------------------------------------------
-- Placeholder table for view `py`.`v_user_lessee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `py`.`v_user_lessee` (`id` INT, `object_id` INT, `lessor_id` INT, `user_id` INT, `remark` INT, `amount` INT, `created_on` INT, `status` INT, `lessor_name` INT, `title` INT, `removed` INT);

-- -----------------------------------------------------
-- Placeholder table for view `py`.`v_user_lessor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `py`.`v_user_lessor` (`id` INT, `object_id` INT, `user_id` INT, `lessee_id` INT, `remark` INT, `amount` INT, `created_on` INT, `status` INT, `lessor_name` INT, `title` INT, `removed` INT);

-- -----------------------------------------------------
-- Placeholder table for view `py`.`v_user_object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `py`.`v_user_object` (`id` INT, `user_name` INT, `user_id` INT, `title` INT, `published_on` INT, `status` INT, `cat_name` INT, `quantity` INT, `invoice_type` INT, `price_month` INT, `price_day` INT, `price_pledge` INT, `return_way` INT, `shortest_lease` INT, `description` INT, `contact_name` INT, `contact_number` INT, `address` INT, `send_way` INT);

-- -----------------------------------------------------
-- Placeholder table for view `py`.`v_user_own_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `py`.`v_user_own_coupon` (`id` INT, `user_id` INT, `coupon_id` INT, `param_1` INT, `param_2` INT, `expiry_date_start` INT, `duration_days` INT, `expiry_date_end` INT, `removed` INT);

-- -----------------------------------------------------
-- View `py`.`v_user_details`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `py`.`v_user_details` ;
DROP TABLE IF EXISTS `py`.`v_user_details`;
USE `py`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `py`.`v_user_details` AS select `u`.`id` AS `id`,`u`.`phone_number` AS `phone_number`,`u`.`email_address` AS `email_address`,`u`.`pwd` AS `pwd`,`u`.`created_on` AS `created_on`,`u`.`status` AS `status`,`ui`.`user_id` AS `user_id`,`ui`.`nick_name` AS `nick_name`,`ui`.`real_name` AS `real_name`,`ui`.`card_no` AS `card_no`,`ui`.`qq_number` AS `qq_number`,`ui`.`identity_valid` AS `identity_valid`,`ui`.`address` AS `address` from (`py`.`user` `u` join `py`.`user_info` `ui`) where (`u`.`id` = `ui`.`user_id`);

-- -----------------------------------------------------
-- View `py`.`v_user_lessee`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `py`.`v_user_lessee` ;
DROP TABLE IF EXISTS `py`.`v_user_lessee`;
USE `py`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `py`.`v_user_lessee` AS select `ull`.`id` AS `id`,`ull`.`object_id` AS `object_id`,`ull`.`lessor_id` AS `lessor_id`,`ull`.`lessee_id` AS `user_id`,`ull`.`remark` AS `remark`,`ull`.`amount` AS `amount`,`ull`.`created_on` AS `created_on`,`ull`.`status` AS `status`,`ui`.`real_name` AS `lessor_name`,`uo`.`title` AS `title`,`ull`.`removed` AS `removed` from ((`py`.`user_lease_logs` `ull` join `py`.`user_object` `uo`) join `py`.`user_info` `ui`) where ((`ull`.`removed` = 0) and (`ull`.`object_id` = `uo`.`id`) and (`ull`.`lessor_id` = `ui`.`user_id`));

-- -----------------------------------------------------
-- View `py`.`v_user_lessor`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `py`.`v_user_lessor` ;
DROP TABLE IF EXISTS `py`.`v_user_lessor`;
USE `py`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `py`.`v_user_lessor` AS select `ull`.`id` AS `id`,`ull`.`object_id` AS `object_id`,`ull`.`lessor_id` AS `user_id`,`ull`.`lessee_id` AS `lessee_id`,`ull`.`remark` AS `remark`,`ull`.`amount` AS `amount`,`ull`.`created_on` AS `created_on`,`ull`.`status` AS `status`,`ui`.`real_name` AS `lessor_name`,`uo`.`title` AS `title`,`ull`.`removed` AS `removed` from ((`py`.`user_lease_logs` `ull` join `py`.`user_object` `uo`) join `py`.`user_info` `ui`) where ((`ull`.`removed` = 0) and (`ull`.`object_id` = `uo`.`id`) and (`ull`.`lessee_id` = `ui`.`user_id`));

-- -----------------------------------------------------
-- View `py`.`v_user_object`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `py`.`v_user_object` ;
DROP TABLE IF EXISTS `py`.`v_user_object`;
USE `py`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `py`.`v_user_object` AS select `o`.`id` AS `id`,(case when isnull(`u`.`phone_number`) then `u`.`email_address` else `u`.`phone_number` end) AS `user_name`,`o`.`user_id` AS `user_id`,`o`.`title` AS `title`,`o`.`published_on` AS `published_on`,`o`.`status` AS `status`,`oc`.`name` AS `cat_name`,`o`.`quantity` AS `quantity`,`o`.`invoice_type` AS `invoice_type`,`o`.`price_month` AS `price_month`,`o`.`price_day` AS `price_day`,`o`.`price_pledge` AS `price_pledge`,`o`.`return_way` AS `return_way`,`o`.`shortest_lease` AS `shortest_lease`,`o`.`description` AS `description`,`o`.`contact_name` AS `contact_name`,`o`.`contact_number` AS `contact_number`,`o`.`address` AS `address`,`o`.`send_way` AS `send_way` from ((`py`.`user_object` `o` join `py`.`user` `u`) join `py`.`object_category` `oc`) where ((`o`.`removed` = 0) and (`o`.`user_id` = `u`.`id`) and (`oc`.`id` = `o`.`cat_id`));

-- -----------------------------------------------------
-- View `py`.`v_user_own_coupon`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `py`.`v_user_own_coupon` ;
DROP TABLE IF EXISTS `py`.`v_user_own_coupon`;
USE `py`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `py`.`v_user_own_coupon` AS select `oc`.`id` AS `id`,`oc`.`user_id` AS `user_id`,`oc`.`coupon_id` AS `coupon_id`,`c`.`param_1` AS `param_1`,`c`.`param_2` AS `param_2`,`oc`.`expiry_date_start` AS `expiry_date_start`,`oc`.`duration_days` AS `duration_days`,(`oc`.`expiry_date_start` + interval `oc`.`duration_days` day) AS `expiry_date_end`,`oc`.`removed` AS `removed` from (`py`.`user_own_coupon` `oc` join `py`.`coupon` `c`) where (`c`.`id` = `oc`.`coupon_id`);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
